# tasks file for roles/database
- name: Run database
  docker_container:
    name: database
    image: scharlet/database
    pull: yes
    env: 
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: usr
      POSTGRES_DB: db
    networks:
      - name: "network_one"