language: java
script:
  # Test and build app
  - mvn clean verify --file ./simple-api/pom.xml

  # Connexion à docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build
  - docker build -t $DOCKER_USERNAME/devops_TP2 simple-api

  # Publication des images
  - docker push $DOCKER_USERNAME/devops_TP2

on:
  branch: develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker