language: java
script:
  # Test and build your app with docker 
  - mvn clean verify --file ./simple-api/pom.xml
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=scharlet_devops_tp2

  # Connexion à docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Build
  - docker build -t $DOCKER_USERNAME/devops_tp2 simple-api

  # docker run -p 8888:5000 --name myfirstapp YOUR_USERNAME/myfirstapp

  # Publication des images
  - docker push $DOCKER_USERNAME/devops_tp2

addons:
  sonarcloud:
    organization: "scharlet"
    token: 
      secure: "$SONARCLOUD_TOKEN"

on:
  branch: develop

cache:
  directories:
    - $HOME/.m2

services:
  - docker